
# main config
auto: false
server: false
lsi: false
exclude: shared
permalink: pretty
posts_include:
  - .textile
  - .markdown
api: true
url: 'http://localhost:4567'
language: en-US
source: posts

keys:
  google_analytics: ""
info:
  address:
    city: Berkeley
    state: CA
    zip: 94704
  email: "lancejpollard@gmail.com"
  website: http://ilove4d.com
  company: 4D
  
metadata:
  domain: ilove4d.com
  title: Cached Commons
  tagline: "Caching and Compressing Javascripts and Stylesheets"
  description: "Caching Universally Common Files, and making it easy to add yours to the cache. Online YUI Compressor, Javascript Compression, and CSS Compression"
  author: "Lance Pollard"
  copyright: "4D | All Rights Reserved"
  country: "United States"
  classification: Techonology and Innovation
  keywords: "Javascript Compression, CSS Compression, YUI Compressor, Online YUI Compressor, Compress, Optimize, gzip, gzip headers"
authors:
  -
    name: Lance Pollard
    age: 23
    city: Berkeley
    state: CA
    zip: 94704
    country: United States
    company: 4D Design Lab
    website: http://github.com/viatropos
links:
  twitter: http://www.twitter.com/viatropos
  facebook: "http://www.facebook.com/viatropos"
  github: http://www.github.com/viatropos/cached-commons
  stack_overflow: ""
  digg: ""
  myspace: ""
  linked_in: ""
  website: "http://www.ilove4d.com"
  google_apps: "http://www.google.com/a/ilove4d.com"
icons:
  favicon: /images/favicon.ico
  touch_icon: /images/touch-icon.jpg